<Project>
  <PropertyGroup>
    <RepositoryArtifactsRoot>$(MSBuildThisFileDirectory)artifacts\</RepositoryArtifactsRoot>
    <ArtifactsProjectName Condition="'$(AssemblyName)' != ''">$(AssemblyName)</ArtifactsProjectName>
    <ArtifactsProjectName Condition="'$(ArtifactsProjectName)' == ''">$(MSBuildProjectName)</ArtifactsProjectName>
    <BaseOutputPath>$(RepositoryArtifactsRoot)build\$(ArtifactsProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(RepositoryArtifactsRoot)build\obj\$(ArtifactsProjectName)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <VSTestResultsDirectory>$(RepositoryArtifactsRoot)test-results\</VSTestResultsDirectory>
  </PropertyGroup>
</Project>
