<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net6.0-windows;net8.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <ApplicationIcon>Assets\OnlyRights.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net6.0-windows'">
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\OnlyRights.ico" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <ProjectReference Include="..\NtfsAudit.Core\NtfsAudit.Core.csproj" />
  </ItemGroup>
</Project>
